# This is a basic workflow to help you get started with Actions

name: Sensuctl Example

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Setup a sensu-backend service
    services:
      sensu-backend:
        image: sensu/sensu:latest
        env: 
          SENSU_BACKEND_CLUSTER_ADMIN_USERNAME: ${{ secrets.SENSU_USER }}
          SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD: ${{ secrets.SENSU_PASSWORD }}
        ports:
          - 8080:8080
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: netstat
      run: netstat -tlpn

    - name: Sensuctl
      uses: ./
      id: sensuctl
      with:
        sensu_backend_url: http://localhost:8080
        sensu_user: ${{ secrets.SENSU_USER }}
        sensu_password: ${{ secrets.SENSU_PASSWORD }} 
        sensu_command: check list --namespace ${{ secrets.SENSU_NAMESPACE }}

